tunnel: 795c612c-a1d6-488e-8045-b62c5a4e8ef7
credentials-file: /home/alex/.config/nobs/795c612c-a1d6-488e-8045-b62c5a4e8ef7.json

ingress:
  - hostname: nobsdash.com
    service: http://127.0.0.1:4173
  - hostname: www.nobsdash.com
    service: http://127.0.0.1:4173
  - service: http_status:404
