#!/usr/bin/env python3
"""Render docs/research/STACK.md from docs/research/stack.json.

The JSON is the source of truth: it is what coding agents load. The Markdown
is the same content laid out for a person to read. Generating one from the
other means they cannot disagree.

    python3 scripts/build_stack_docs.py           # write STACK.md
    python3 scripts/build_stack_docs.py --check   # fail if STACK.md is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs" / "research" / "stack.json"
OUTPUT = ROOT / "docs" / "research" / "STACK.md"

# Display order and headings for the `layer` field.
LAYERS = [
    ("backend", "Tank backend (Python)"),
    ("tooling", "Developer tooling"),
    ("apple", "Apple platform"),
    ("website", "Website"),
    ("local-ai", "Local AI"),
    ("smart-home", "Smart home"),
    ("infrastructure", "Infrastructure"),
]


def render(data: dict) -> str:
    lines: list[str] = []
    add = lines.append

    add("# NOBS stack reference")
    add("")
    add("<!-- Generated by scripts/build_stack_docs.py from stack.json. Do not edit by hand. -->")
    add("")
    add(data["purpose"])
    add("")
    add(
        f"**{len(data['entries'])} entries.** The machine-readable source is "
        "[`stack.json`](stack.json); this page is generated from it."
    )
    add("")
    add("## Rules any new dependency has to clear")
    add("")
    for constraint in data["constraints"]:
        add(f"- {constraint}")
    add("")

    by_layer: dict[str, list[dict]] = {}
    for entry in data["entries"]:
        by_layer.setdefault(entry["layer"], []).append(entry)

    known = {layer for layer, _ in LAYERS}
    unknown = sorted(set(by_layer) - known)
    if unknown:
        raise SystemExit(f"stack.json uses layers with no heading defined: {unknown}")

    add("## Contents")
    add("")
    for layer, heading in LAYERS:
        if by_layer.get(layer):
            anchor = heading.lower().replace(" ", "-").replace("(", "").replace(")", "")
            add(f"- [{heading}](#{anchor}) — {len(by_layer[layer])}")
    add("")

    for layer, heading in LAYERS:
        entries = by_layer.get(layer)
        if not entries:
            continue
        add(f"## {heading}")
        add("")
        for entry in sorted(entries, key=lambda e: e["name"].lower()):
            version = entry.get("resolved") or entry.get("declared")
            title = f"### {entry['name']}"
            if version:
                title += f" `{version}`"
            add(title)
            add("")
            add(f"*{entry['category']}* — {entry['role']}")
            add("")
            add(f"**Why it is here.** {entry['why_here']}")
            add("")
            if entry.get("used_in"):
                paths = ", ".join(f"`{p}`" for p in entry["used_in"])
                add(f"**Used in.** {paths}")
                add("")
            if entry.get("learn"):
                add(f"**Worth knowing.** {entry['learn']}")
                add("")
            if entry.get("alternatives"):
                add("**Alternatives.**")
                add("")
                for alt in entry["alternatives"]:
                    add(f"- **{alt['name']}** — {alt['when']}")
                add("")
            add(f"[Documentation]({entry['docs']})")
            add("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if STACK.md is out of date")
    args = parser.parse_args()

    rendered = render(json.loads(DATA.read_text(encoding="utf-8")))

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(
                "docs/research/STACK.md is out of date. Run: python3 scripts/build_stack_docs.py",
                file=sys.stderr,
            )
            return 1
        print("docs/research/STACK.md is up to date.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
