#!/usr/bin/env bash
# nobs-obsidian-export — Unified brain database, loop logs, and campaign queue exporter
set -eu

V="/home/alex/Obsidian-Vault"
mkdir -p "$V/Logs" "$V/Campaigns" "$V/Proposals" "$V/RSS-Feeds"

# 1. Export Active Automation Loop Logs
for log in auto-approve website-improve ios-improve content-ideas rss-digest seo-audit blog-draft; do
    file="$V/Logs/nobs-$log.md"
    echo "Writing logs for $log..."
    
    # Get last 50 lines safely
    log_content=""
    if [ -f "/home/alex/logs/nobs-$log.log" ]; then
        log_content=$(tail -n 50 "/home/alex/logs/nobs-$log.log")
    else
        log_content="(No log data available)"
    fi

    cat << EOF > "$file"
---
title: "Log: nobs-$log"
updated: $(date -Is)
tags: [system, logs, autopilot]
---
# nobs-$log.service Loop Activity

\`\`\`text
$log_content
\`\`\`
EOF
done

# 2. Export SQLite Campaign Queue
echo "Exporting SQLite Campaigns..."
campaigns_file="$V/Campaigns/Campaign-Queue.md"
cat << 'EOF' > "$campaigns_file"
---
title: Campaign Queue
updated: $(date -Is)
tags: [campaigns, agency, queue]
---
# SQLite Campaign Database (agency.db)

Here are the latest content pieces and social drafts managed by the NOBS Agency stack.

## Active Content Queue
EOF

# Append sqlite query as a formatted markdown table
sqlite3 -header -markdown /home/alex/production/nobs-agency/agency.db "SELECT id, platform, headline, status, created_at FROM content_pieces ORDER BY id DESC LIMIT 50;" >> "$campaigns_file"

# Write individual detailed draft notes
echo "Generating draft markdown note files..."
rm -f "$V/Campaigns"/Draft-*.md

# Select only drafts as JSON and iterate safely
sqlite3 -json /home/alex/production/nobs-agency/agency.db "SELECT id, platform, headline, body, status FROM content_pieces WHERE status='draft' LIMIT 15;" | jq -c '.[]' | while read -r row; do
    id=$(echo "$row" | jq -r '.id')
    platform=$(echo "$row" | jq -r '.platform')
    headline=$(echo "$row" | jq -r '.headline')
    body=$(echo "$row" | jq -r '.body')
    status=$(echo "$row" | jq -r '.status')

    # Keep only alphabetic, numeric, and hyphens in the filename slug
    slug=$(echo "$headline" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-' | head -c 40)
    [ -z "$slug" ] && slug="draft-$id"
    
    cat << EOF > "$V/Campaigns/Draft-$slug.md"
---
id: $id
platform: $platform
status: $status
tags: [campaign, draft, $platform]
---
# $headline

* **Platform**: $platform
* **Status**: ✏️ $status

## Content Body
$body
EOF
done

# 3. Export RSS Digests
echo "Syncing RSS digests..."
for rss in latest week; do
    src="/home/alex/logs/rss-$rss.md"
    dest="$V/RSS-Feeds/rss-$rss.md"
    if [ -f "$src" ]; then
        cat << EOF > "$dest"
---
title: "RSS Feed: $rss"
updated: $(date -Is)
tags: [rss, digest]
---
$(cat "$src")
EOF
    fi
done

# 4. Export Development Proposals Queue
echo "Syncing Dev Queue..."
proposals_file="$V/Proposals/Development-Queue.md"
cat << 'EOF' > "$proposals_file"
---
title: Autopilot Proposals Queue
updated: $(date -Is)
tags: [autopilot, proposals, queue]
---
# Active Autopilot Proposals Queue

These are the latest development proposals generated by the local models in the autopilot queue.

## Queue Status
EOF

if [ -f "/home/alex/logs/openhands-queue.jsonl" ]; then
    jq -r '["Title", "Category", "Queued At"], ["-", "-", "-"], (.[] | [.title, .category, .queued_at]) | @tsv' <(echo "[]"; cat /home/alex/logs/openhands-queue.jsonl | jq -s '.') | sed 's/\t/ | /g' | sed 's/^/| /g' | sed 's/$/ |/g' >> "$proposals_file"
else
    echo "Queue is empty." >> "$proposals_file"
fi

# 5. Git Commit & Push
echo "Committing and pushing brain database updates..."
git -C "$V" add -A
if ! git -C "$V" diff-index --quiet HEAD --; then
    git -C "$V" commit -m "Auto-sync live system brain state: $(date +'%Y-%m-%d %H:%M:%S')"
    git -C "$V" push origin main
    echo "Updates pushed to GitHub successfully!"
else
    echo "No brain changes detected, skipping commit."
fi
